site_name: "Física Contemporánea" 
docs_dir: "pages"
  
theme:
  name: material

markdown_extensions:
  - mdx_math:
      enable_dollar_delimiter: True
  - pymdownx.arithmatex:
      generic: true
  - attr_list
  - md_in_html
  - pymdownx.blocks.caption
     
extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js
  
extra_css:
  - stylesheets/custom.css